### ISSUE TITLE
Multiple identity center instances set up

### ISSUE THREAD

**Issue by 2stevewonder** [benkehoe/aws-sso-util#103]
I am having issues setting up the aws-sso-util tool that you've created and I have configured two identity center instances by accident. This is causing some issues with the configuration of the profiles and the login as well. Is there a way to remove one of the identity centers? I cannot seem to find where it stores the start urls.

**Comment by benkehoe** [comment]
The documentation for how `aws-sso-util` resolves Identity Center instances is in the docs pages, for instance for login it's [here](https://github.com/benkehoe/aws-sso-util/blob/master/docs/login.md#identity-center-instances) (there are some small differences between commands, mostly command-specific environment variables). My guess would be that your AWS config file at `~/.aws/config` has contains profiles with one instance and other profiles with the other instance. Cleaning that out would be my suggestion for the first step.

**Comment by 2stevewonder** [comment]
I removed the profiles in the config file and it worked. Thank you!
