### ISSUE TITLE
Reset all SSO config and set new SSO url

### ISSUE THREAD

**Issue by throrin19** [benkehoe/aws-sso-util#124]
Hello,
I try, with no success, to change my SSO information : we restructure all our organizations schema and, after that, our SSO url has changed (not in same account).

I try to login into new URL but I have this error : 

```
No Identity Center instance matched https://d-aaaaaa.awsapps.com/start[None] from https://d-bbbbbb.awsapps.com/start
```

I try to change the global configuration with : 

```
aws-sso-util configure populate --existing-config-action overwrite -u https://d-aaaaaa.awsapps.com/start --region eu-west-1
```

But I have the same error.

Have you a function like `reset` to reset all configuration and start from zero ?

**Comment by iainelder** [comment]
Hi @throrin19. I don't know any `reset` function.

aws-sso-util writes to the standard AWS CLI config file.

By default it is located in your home folder at `.aws/config`.

If it's not there then check the [AWS_CONFIG_FILE](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html) environment variable. You can set that to override the location.

If you have that file, and it still refers to the old instance, then make a backup copy of the file and then delete the original.

Then run the `configure populate` command again. It should now work as you expect.

**Comment by throrin19** [comment]
I found how to do this : 

```
aws-sso-util configure populate --existing-config-action overwrite -u https://new_id.awsapps.com/start --region eu-west-1 --sso-region eu-west-1
```

That command override latest known sso url and you can connect again. You don't need to remove `.aws/config` with it, the command override all config with new login informations

**Comment by iainelder** [comment]
Thanks for coming back with your solution. It's neater than my suggestion.
