### ISSUE TITLE
Surround Profile Names with Spaces in Single Quotes

### ISSUE THREAD

**Issue by M1kep** [benkehoe/aws-sso-util#16]
When using aws-sso-util configure populate, it creates the config with profile names having spaces. This seems to break the AWS cli --profile flag. According to this issue( https://github.com/aws/aws-cli/issues/2806 ) surrounding the profile names with Single Quotes fixes the issue. I've tested this locally and it appears to fix the issue.

**Comment by benkehoe** [comment]
I'm curious--these are spaces in the account names? I think I can fix it.

**Comment by M1kep** [comment]
Yep exactly,

In this case it'd be something like "Mike Dev Tenant.Administrator". From what I read in the linked issue and tested, just adding single quotes around that should solve it. I took a look at the code, but for what would most likely be a quick fix for you, I can't quite wrap my head around where the profile naming is coming from.

Thanks!

**Comment by benkehoe** [comment]
Turns out `aws configure sso` in the CLI v2 still has this problem. I use that code in `aws-sso-lib` to write the profiles. I copied in the fix from that issue. I'm having PyPI issues, I'll get it sorted tomorrow.

**Comment by benkehoe** [comment]
Fixed in CLI v2.19

**Comment by benkehoe** [comment]
ugghhh when they implemented `aws configure sso`, they didn't put the profile name quoting in the thing that writes to the config file, they put it upstream of that. Which is a poor choice, for obvious reasons.
