### ISSUE TITLE
Updates to SSO timestamp format

### ISSUE THREAD

**Issue by nateprewitt** [benkehoe/aws-sso-util#18]
Hi @benkehoe,

We recently found a bug in botocore that's been producing an unintended timestamp for SSO credentials. We've decided to fix the format (boto/botocore#2250) to prevent additional issues with the other AWS SDKs. We know you've been doing a lot of work with SSO and wanted to make sure this change was on your radar. Please let us know if you have any feedback or thoughts on the change.

Thanks!

**Comment by benkehoe** [comment]
Awesome, and thanks for letting me know! I've updated my code to pull `SSOCredentialFetcher` from botocore directly, leaving only `SSOTokenFetcher` vendored from the v2 branch. This change should eventually make it into the v2 branch and thus the AWS CLI v2 as well, right?

**Comment by nateprewitt** [comment]
That's correct. Once the PR is merged, you should see the change in both the botocore v2 and CLI v2 branches during their next release.

**Comment by nateprewitt** [comment]
Hey again @benkehoe, we made some minor changes to the datetime fix. It's moved to a class var instead of the helper function to alleviate some of your concerns. It should be available in the next releases of CLI v2, feel free to close this if you don't have further tracking actions.

**Comment by benkehoe** [comment]
I don't have any further concerns, as I'll leave the remediation code in place for people with old versions, and when I update to use `SSOCredentialFetcher` directly from botocore, I'll get your changes.

Thanks so much!
