### ISSUE TITLE
Remove single quotes and spaces from profile names

### ISSUE THREAD

**Issue by hoegertn** [benkehoe/aws-sso-util#21]
There are several issues with the current variant:

- spaces are error-prone as everything needs to be quoted (e.g the credentials_process is missing them)
- the JS SDK seems to break with single quotes in the profile name (it just doesn't find it at all)

Solution?

I would recommend removing all spaces from the account name when generating profile names.

In my scripts I normally do:
```
const safeName = acc.Name.replace(/[^A-Za-z0-9-]/g, '-').replace(/-+/g, '-').toLowerCase();
```

**Comment by benkehoe** [comment]
Hm, yeah. For the second bullet, you're saying if the profile name itself has a single quote in it, or if a profile name is quoted in single quotes?

I am a little uncomfortable automatically flattening quote-needing profile names, in case somebody has a situation where two accounts would translate to the same name, but I could add a `--safe-profile-names` flag?

**Comment by hoegertn** [comment]
The profile name was quoted in the config file `[profile 'some name with spaces']`. This broke the JS SDK.

I see the problem with duplicate safe names but IMHO the current solution just does not work for these accounts. So duplicate profile names or broken ones do not make a difference. But it would be great to fail on duplicates to make the problem transparent.

**Comment by benkehoe** [comment]
I think I will implement the "safe account names" by default, and not address duplicates at this time, but allow it to be disabled. Can you open a ticket with the JS SDK that they do not correctly parse the config files?

**Comment by benkehoe** [comment]
I am going to implement this as `s/[^A-Za-z0-9-._]+/-/g`, any objections?

**Comment by hoegertn** [comment]
Sounds great. Maybe you want to deduplicate dashes afterwards. I will investigate the JS SDK issue and open a ticket.

**Comment by benkehoe** [comment]
Makes sense. `s/-*[^A-Za-z0-9-._]+-*/-/g` then

**Comment by benkehoe** [comment]
The JS SDK problem happens here: https://github.com/aws/aws-sdk-js/blob/a8edd6d37fd42bb1e35907124b3f5328ba7bbc86/lib/shared-ini/ini-loader.js#L10

**Comment by benkehoe** [comment]
Seeing that, I'm tempted to say the replace should only be for `[\s]+`

**Comment by benkehoe** [comment]
Oof.

golang doesn't even support anything other than exactly "profile " as a prefix. https://github.com/aws/aws-sdk-go/blob/039c0ff7b11be2b2d94477e47e56d980a9f1e3e6/aws/session/shared_config.go#L276

Java removes "profile" and then trims whitespace. https://github.com/aws/aws-sdk-java-v2/blob/61f6c94f6426fe6395f3f5dd6f1f4c520987ca3a/core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java#L198

Ruby may not even work with ~/.aws/config profile names, I can't tell in here where it does that https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb

**Comment by hoegertn** [comment]
JS SDK v3 seems to parse it correctly.

**Comment by benkehoe** [comment]
Yep, it's now `/^profile\s(["'])?([^\1]+)\1$/`. Still a problem in other SDKs, though.
https://github.com/aws/aws-sdk-js-v3/blob/314d3b37ac9d0d500e5762705be6188d9bd69625/packages/shared-ini-file-loader/src/index.ts#L57

**Comment by benkehoe** [comment]
I've made this changes as CLI version 4.22. Let me know if it's all working for you. I'm still looking for good ways to be able to create a test suite for this, given that it depends so highly on Orgs and AWS SSO APIs, and on so many languages.

**Comment by hoegertn** [comment]
LGTM! multiple dashes are not merged into one but everything is working fine.

**Comment by benkehoe** [comment]
That's correct; given that it's only spaces that were replaced, I'm not expecting that it's too common that spaces adjoin dashes, and then it's also less likely that it will fold two account names down to the same value.
