### ISSUE TITLE
`aws-sso-util --help` fails on Python 3.6

### ISSUE THREAD

**Issue by jaden-young** [benkehoe/aws-sso-util#22]
Installed `aws-sso-util` with pipx on Ubuntu WSL. Attempting to run results in a stacktrace:

![aws-sso-util-python-3 6-bug](https://user-images.githubusercontent.com/9858187/102921514-1aa59b80-4452-11eb-975c-f5dd2a8302a2.png)

Tracking down the offending line:

https://github.com/benkehoe/aws-sso-util/blob/023140e8b8cf71dc5c3f4428eab55517e402bd47/lib/aws_sso_lib/sso.py#L204

`typing.Literal` was introduced in [Python 3.8](https://docs.python.org/3/library/typing.html#typing.Literal)

Looking at the blame it seems to have been introduced in [lib-v1.4](https://github.com/benkehoe/aws-sso-util/releases/tag/lib-v1.4).

**Comment by benkehoe** [comment]
I have fixed this in lib-v1.6/cli-v4.22.
