### ISSUE TITLE
Show known components in populate help

### ISSUE THREAD

**Issue by iainelder** [benkehoe/aws-sso-util#33]
Would it be possible to show the known components in the online help for `aws-sso-util configure populate`?

I was trying to find a way to remove the role name from the generated profile names. In my environment I have the same single role available in all the accounts, so its name is redundant.

The online help hints that it is possible to control the elements of the profile name, but doesn't give any detail about what the valid components are. 

```
  --components VALUE,VALUE,...    Profile name components to join (comma-
                                  separated)
```

I had to refer to the code on Github to get the answer (`--components account_name`).
 
https://github.com/benkehoe/aws-sso-util/blob/c69c70ecf41eabcad251a489df01833fc35cae76/cli/src/aws_sso_util/populate_profiles.py#L68-L75

Would it be possible to include the known components in the online help to make the command easier to use?

**Comment by benkehoe** [comment]
If I understand correctly, you're saying you want them in the help output by the command, that the [docs here](https://github.com/benkehoe/aws-sso-util/blob/master/docs/configure.md#components-and-separator) are not enough? That seems reasonable, I can put it in there for the next release. I'll leave this issue open until it's done.

**Comment by iainelder** [comment]
Hi, @benkehoe, thanks for the link to the documentation. I had missed that page on first reading before diving in.

Now that I've seen that, I would be happy to close this without any changes. I had mistakenly thought the values were undocumented.

Thanks so much for this tool in any case. It makes working with AWS SSO a more friendly experience.

**Comment by benkehoe** [comment]
It makes sense to have the list of values in the command-line help as well, even if it's not explained as thoroughly as in the docs.

**Comment by benkehoe** [comment]
This is released in [CLI v4.26](https://github.com/benkehoe/aws-sso-util/blob/master/CHANGELOG.md#cli-v426)

**Comment by iainelder** [comment]
The output of `aws-sso-util configure populate --help` now shows:

```
  --components VALUE,VALUE,...    Profile name components to join (comma-
                                  separated). Possible values are:
                                  account_name account_id account_number
                                  role_name region short_region
```

Just as I had imagined it. This is functions as a memory aid, and the documentation provides a space for a detailed analysis.

It seems like a small improvement, but it means a lot. The structure of your Github projects and  your writing about boto3 programming have inspired me to maintain my own set of AWS utilities written in Python.

Keep up the good work :-)

**Comment by benkehoe** [comment]
Sorry it took so long for a release to come out to ship it.
