### ISSUE TITLE
Support for setting env variables

### ISSUE THREAD

**Issue by reidca** [benkehoe/aws-sso-util#34]
Looking at this tool to see if it can help me with a problem using some third party binaries that only work with AWS env variables containing access credentials.

Does this tool support writing out env variables after login? Not clear from docs.

Thanks

**Comment by arledesma** [comment]
@reidca are you looking for the functionality provided by [benkehoe/aws-export-credentials](https://github.com/benkehoe/aws-export-credentials)?

**Comment by reidca** [comment]
> @reidca are you looking for the functionality provided by [benkehoe/aws-export-credentials](https://github.com/benkehoe/aws-export-credentials)?

Thank you very much, perfect!
