### ISSUE TITLE
Feature Request: Create Homebrew Package

### ISSUE THREAD

**Issue by joel-aws** [benkehoe/aws-sso-util#37]
It would be really awesome to have aws-sso-util in Homebrew as a package that could easily be installed system-wide. This is a feature-request to get that integrated.

**Comment by Shumakriss** [comment]
As a Python user, I'd prefer to just use pip. Right now the instructions require me to install pipx. 

Speaking for non-Python developers, I think I would rather avoid brew altogether and just have a .dmg install.

**Comment by knoxilla** [comment]
Looks like this is done!

**Comment by benkehoe** [comment]
For future reference, I guess to maintain this going forward, I need to use https://github.com/tdsmith/homebrew-pypi-poet to create updates to https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-sso-util.rb
I've never done such a thing before, so we'll see how it goes in the next release. If it works, I'll add it to the install instructions.
