### ISSUE TITLE
Finer-grained profile regions

### ISSUE THREAD

**Issue by mikeknep** [benkehoe/aws-sso-util#62]
### Description
I'd like to have finer-grained control over each profile's region during `aws-sso-util configure populate`. For example, if I have roles for separate workflows dealing with services in Ireland vs. Oregon, I'd like to ultimately end up with a config file that looks like this:

```
[profile myaccount.european]
sso_start_url = https://myaccount.awsapps.com/start#
sso_region = us-west-2
sso_account_name = MyAccount
sso_account_id = 111111111111
sso_role_name = European
region = eu-west-1
credential_process = aws-sso-util credential-process --profile myaccount.european
sso_auto_populated = true

[profile myaccount.american]
sso_start_url = https://myaccount.awsapps.com/start#
sso_region = us-west-2
sso_account_name = MyAccount
sso_account_id = 111111111111
sso_role_name = American
region = us-west-2
credential_process = aws-sso-util credential-process --profile myaccount.american
sso_auto_populated = true
```
I don't want to "prioritize" one region over the other (e.g. if you're in eu-west-1 you must append a region suffix to the profile name, but if you're in us-west-2 the region is implicit).

I also don't want to _always_ specify the region, since it's more typing and the role names already make it clear where I am/want to be. More importantly, though, even if I pass multiple regions to generate the cross-product of roles and regions _and_ specify `--include-region always`, I'm left with what are effectively "nonsensical" profiles like `myaccount.european.us-west-2` or `myaccount.american.eu-west-1`.

(This example uses role names, but one might alternatively have separate accounts for different regional workloads, in which case I'd want to use the account name to determine the profile region.)

### Implementation idea
One possibility I explored was to pass multiple regions (to generate a cross product as described above) *and* define a custom name formatter to pass to `--profile-name-process` that only prints profile name values for "valid" combinations, e.g.:
```
if valid_role_region_combination(role, region):
    print(profile_name)
```
However, this results in an empty-string profile being created:
```
[profile ]
sso_start_url = https://myaccount.awsapps.com/start#
# ...
```
If profiles with empty string names were dropped from the final output collection, I think I'd have everything I need via the profile name process command. Furthermore, an empty string profile name is probably invalid anyways, so perhaps this approach makes additional sense for that reason?

Thanks for this great tool!

**Comment by benkehoe** [comment]
I'll think about this a bit more, but I realized I don't have in the documentation that you can return the value `SKIP` from the profile name process to avoid including a particular configuration as a profile. https://github.com/benkehoe/aws-sso-util/blob/dc021144c825940e50da1a241f9b1cc6a7d8322d/cli/src/aws_sso_util/populate_profiles.py#L357

**Comment by benkehoe** [comment]
I think I should make it an error to return an empty string from a profile name process, since that's invalid and likely a mistake.

**Comment by mikeknep** [comment]
Oh, nice! Thanks for the quick reply and pointer to SKIP—just tested and that'll work for me.
