### ISSUE TITLE
Unable to create profile in aws configure sso and unable to go to path ~/ .aws/config using aws cli V2 on Amazon Linux 2

### ISSUE THREAD

**Issue by surendranathr** [benkehoe/aws-sso-util#65]
Unable to create profile in aws configure sso and unable to go to path ~/ .aws/config using aws cli V2 on Amazon Linux 2.
No such file or directory when we are trying to go to the .aws/config

**Comment by benkehoe** [comment]
If you're having issues with `aws configure sso`, that's not a problem caused by aws-sso-util. It sounds like maybe it's a directory permissions/ownership problem. You'll want to open an issue with the AWS CLI: https://github.com/aws/aws-cli/issues
