### ISSUE TITLE
login doesn't log in

### ISSUE THREAD

**Issue by kapet** [benkehoe/aws-sso-util#74]
This didn't happen a month ago but now regularly does. Using awsume to assume a role. First it works, then after the token has expired, I'm unable to refresh it. Here is an example using just aws-sso-util:

% aws-sso-util credential-process --profile ACCOUNT
Login required. Use `aws-sso-util login --profile ACCOUNT` or `aws sso login --profile ACCOUNT` and try again.

% aws-sso-util login --profile ACCOUNT
Logging in https://DOMAIN.awsapps.com/start
Login succeeded, valid until 2022-10-06 00:10 CEST

% aws-sso-util credential-process --profile ACCOUNT
Login required. Use `aws-sso-util login --profile ACCOUNT` or `aws sso login --profile ACCOUNT` and try again.

Enabling debug output is not conclusive. The login function ends with this line:
INFO:aws_sso_util.login:Login succeeded, valid until 2022-10-06 00:10 CEST
And the credential-process shows this around the end:
DEBUG:botocore.parsers:Response body: b'{"message":"Session token not found or invalid","__type":"com.amazonaws.switchboard.portal#UnauthorizedException"}'

Only way to recover is to run login with --force.

Any idea what's going on? Is this a bug in the aws cli?

Thanks!

aws-sso-util 4.29.0
aws-cli 2.8.0

**Comment by benkehoe** [comment]
Can you run `aws-sso-util check --account-id ACCOUNT_ID --role-name ROLE_NAME -vvv` for the values you have in your profile? I should add an option to that command to pull the config from a profile.

**Comment by kapet** [comment]
Thanks Ben and sorry for the delay. I was on the lookout for the issue but it just stopped happening. I'll reopen if it reappears.
