### ISSUE TITLE
Recursive assignments try to deploy to accounts in the `SUSPENDED` state

### ISSUE THREAD

**Issue by Anton0** [benkehoe/aws-sso-util#80]
When using the Cloudformation macro and pointing an Assignment recursively at the root id `r-xxx` the output template will attempt to create assignments for accounts in a Suspended state - this eventually times out and fails, and of course Cloudformation then rolls everything back

```
Resource handler returned message: "Error occurred during operation 'Request REDACTED failed due to: 
AWS SSO is unable to complete your request at this time. 
Obtaining permissions to manage your AWS account 'REDACTED' is taking longer than usual.
```

**Comment by benkehoe** [comment]
Released in [aws-sso-lib v1.14](https://github.com/benkehoe/aws-sso-util/blob/next/CHANGELOG.md#lib-v114) and [aws-sso-util v4.31](https://github.com/benkehoe/aws-sso-util/blob/next/CHANGELOG.md#cli-v431).
