### ISSUE TITLE
custom browser

### ISSUE THREAD

**Issue by bartsimp** [benkehoe/aws-sso-util#82]
Hello, 

would it be possible to specify which browser to use? not the default one

Thanks

**Comment by benkehoe** [comment]
You can do it already! aws-sso-util uses Python's [`webbrowser` module](https://docs.python.org/3/library/webbrowser.html) to open the browser. You can set the `BROWSER` environment variable to one of the names it understands or to a system command for opening the browser. See the [docs](https://docs.python.org/3/library/webbrowser.html) for details.
