### ISSUE TITLE
Please upgrade to click 8

### ISSUE THREAD

**Issue by wichert** [benkehoe/aws-sso-util#85]
aws-sso-util uses click v7. This is not compatible with [black](https://black.readthedocs.io/en/stable/), which requires click v8. This is a bit problematic for me since I'm working on a package that calls into some aws-sso-util cli internals (`get_token_fetcher` in particular), and I can't run black to enforce consistent coding style due to this conflict.

**Comment by jorenverspeurt** [comment]
Seconding (thirding?) this. Black is so widely used that by depending on the old click version you're severely limiting the environments this library can be installed in.

**Comment by benkehoe** [comment]
Things have been going slower this month for me than I planned, but I will have it this week. However, I'm interested in your (@wichert @Almenon @jorenverspeurt) usage of `aws-sso-util` as a library.  `aws-sso-util` is intended to be installed as a standalone utility (e.g., through pipx); all library use cases are supposed to be supported through [`aws-sso-lib`](https://github.com/benkehoe/aws-sso-util/blob/master/lib/README.md), which doesn't use click at all. As an example, [`get_token_fetcher()` is in `aws_sso_lib.sso`](https://github.com/benkehoe/aws-sso-util/blob/bb8b3c8f3eab7ffe9ad5190c7cb260d0769be516/lib/aws_sso_lib/sso.py#L60), it's not actually in the `aws-sso-util` code at all.

**Comment by wichert** [comment]
After some recent refactoring we still have a dependency on `aws-sso-util` to have `aws-sso-util credential-process` available for use in profile configuration.

**Comment by benkehoe** [comment]
Are you sure you still need `aws-sso-util credential-process`? Almost all the language SDKs support SSO configuration now.

I haven't touched the standalone credential process I made since I folded it into aws-sso-util but it might still work and doesn't use click: https://github.com/benkehoe/aws-sso-credential-process

**Comment by benkehoe** [comment]
Released in [aws-sso-util v4.31](https://github.com/benkehoe/aws-sso-util/blob/next/CHANGELOG.md#cli-v431).
